CREATE TABLE IF NOT EXISTS public."Players"
(
    id bigint NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    birthday character varying(255) COLLATE pg_catalog."default" NOT NULL,
    height character varying(255) COLLATE pg_catalog."default" NOT NULL,
    state character varying(255) COLLATE pg_catalog."default",
    city character varying(255) COLLATE pg_catalog."default",
    street character varying(255) COLLATE pg_catalog."default",
    gender character varying(255) COLLATE pg_catalog."default" NOT NULL,
    age character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(255) COLLATE pg_catalog."default" NOT NULL,
    not_hashed_password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    bio text COLLATE pg_catalog."default",
    prefered_sport character varying(255) COLLATE pg_catalog."default" NOT NULL,
    balance integer NOT NULL,
    email_verified boolean NOT NULL,
    phone_verified boolean NOT NULL,
    terms_conditions boolean NOT NULL,
    blocked boolean NOT NULL,
    notification_invites boolean NOT NULL,
    notification_messages boolean NOT NULL,
    notification_reminders boolean NOT NULL,
    notification_promotions boolean NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "Players_pkey" PRIMARY KEY (id),
    CONSTRAINT "Players_email_key" UNIQUE (email)
);